# .goreleaser.yml
# Build customization
builds:
  - binary: cortado
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
brew:
  # Name of the recipe
  # Default to project name
  name: cortado

  # Reporitory to push the tap to.
  github:
    owner: nodefortytwo
    name: homebrew-tap

  # Allows you to set a custom download strategy.
  # Default is empty.
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Caveats for the user of your binary.
  # Default is empty.
  caveats: "who knows"

  # Your app's homepage.
  # Default is empty.
  homepage: ""

  # Your app's description.
  # Default is empty.
  description: "testing"