# .goreleaser.yml
# Build customization
builds:
  - binary: cortado
    goos:
      - darwin
      - linux
    goarch:
      - amd64
brew:
  # Name of the recipe
  # Default to project name
  name: cortado

  # Reporitory to push the tap to.
  github:
    owner: nodefortytwo
    name: homebrew-tap

  # Allows you to set a custom download strategy.
  # Default is empty.
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Your app's homepage.
  # Default is empty.
  homepage: ""

  # Your app's description.
  # Default is empty.
  description: "Very simple S3 file editor that temporarily downloads a file from S3, opens it in vim and re-uploads it when you exit vim"